FROM docker.io/alpine:3.20.2
RUN apk add --update --no-cache python3 openssl
WORKDIR /usr/src/hostinfo
COPY ./__main__.py .
RUN chown 1000:1000 __main__.py && chmod 500 __main__.py
LABEL org.opencontainers.image.ref.name=hostinfo
LABEL org.opencontainers.image.version=1.0.0-python
LABEL org.opencontainers.image.authors=rx-m
LABEL org.opencontainers.image.url=https://rx-m.com
USER 1000:1000
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["./__main__.py"]
CMD ["9898"]